= Apache Causeway - Nightly Builds
:toc:
:toc-title: pass:[<h3>Contents</h3>]
:toc-placement!:

[WARNING]
====
The project is currently undergoing a renaming from _Apache Isis_ to _Apache Causeway_ - links might be not working yet or links and names might be outdated!
====

image:https://github.com/apache-causeway-committers/causeway-nightly/actions/workflows/apache-causeway-ci-nightly.yml/badge.svg[link="https://github.com/apache-causeway-committers/causeway-nightly/actions/workflows/apache-causeway-ci-nightly.yml"]

____
https://causeway.apache.org[Apache Causeway] software is a framework for rapidly developing domain-driven apps in Java.
Write your business logic in entities, domain services and repositories, and the framework dynamically generates a representation of that domain model as a webapp or a RESTful API.
____

toc::[]

==  What is built here?

The following are built and published nightly:

Projects::
  * link:https://github.com/apache-causeway-committers/causeway-nightly/tree/master/mvn-snapshots/org/apache/causeway[Apache Causeway]
  ** `2.x Snapshots`: _Spring Framework_ 5.x, _Java_ 11
  ** `3.x Snapshots`: _Spring Framework_ 6.x, _Java_ 17 
  * link:https://github.com/apache-causeway-committers/causeway-nightly/tree/master/mvn-snapshots/org/apache/isis[Apache Isis (Legacy)]
  ** `2.x Snapshots`: _Spring Framework_ 5.x, _Java_ 11 (EOL, to be removed June '23)
Docker Images::
  * Demo (Wicket/JDO) link:https://hub.docker.com/r/apacheisis/demo-wicket-jdo[apacheisis/demo-wicket-jdo (published on Docker Hub)] 
  * Demo (Wicket/JPA) link:https://hub.docker.com/r/apacheisis/demo-wicket-jpa[apacheisis/demo-wicket-jpa (published on Docker Hub)]
Web Sites::
  * Apache Causeway Site link:https://apache-causeway-committers.github.io/causeway-nightly[Nightly Preview] 

  
Also see https://github.com/apache/causeway/tree/master/examples/demo[demo-sources] 
for details and on how to get started.

== Snapshot Repository (Maven)
____
Notes on https://cwiki.apache.org/confluence/display/ISIS/Semantic+Versioning+of+Staged+Builds[Semantic Versioning of Staged Builds].
____

Inspect available versions::
  * `Apache Causeway builds`: link:https://raw.githubusercontent.com/apache-causeway-committers/causeway-nightly/master/mvn-snapshots/org/apache/causeway/causeway-bom/maven-metadata.xml[Version Catalog (XML)]
  * `Apache Isis legacy builds`: link:https://raw.githubusercontent.com/apache-causeway-committers/causeway-nightly/master/mvn-snapshots/org/apache/isis/isis-bom/maven-metadata.xml[Version Catalog (XML)]

[source,xml]
.To use the Maven artifacts _Apache Causeway_ (or former _Apache Isis_), add the following definition into your `pom.xml`:
----
<profiles>
  <profile>
    <id>causeway-nightly-snapshots</id>
    <activation>
      <property>
        <name>!skip.causeway-nightly-snapshots</name>
      </property>
    </activation>
    <repositories>
      <repository>
        <releases>
          <enabled>true</enabled>
          <updatePolicy>always</updatePolicy>
          <checksumPolicy>fail</checksumPolicy>
        </releases>
        <snapshots>
          <enabled>true</enabled>
          <updatePolicy>always</updatePolicy>
          <checksumPolicy>fail</checksumPolicy>
        </snapshots>
        <id>causeway-nightly-snapshots</id>
        <name>Causeway Nightly Snapshots (maven)</name>
        <url>https://raw.githubusercontent.com/apache-causeway-committers/causeway-nightly/master/mvn-snapshots</url>
      </repository>
    </repositories>
  </profile>
</profiles>
----

== Code Quality (Sonar)

See our Sonarcloud link:https://sonarcloud.io/dashboard?id=apache_isis[Dashboard]. 
